const API_BASE_URL = process.env.NEXT_PUBLIC_REACT_APP_API_BASE_URL;
export const Inventory = {
  GetPartCategoryList: `${API_BASE_URL}InventoryWeb/GetPartCategoryList`,
  GetPartBrandList: `${API_BASE_URL}InventoryWeb/GetPartBrandList`,
  PostPartCategory: `${API_BASE_URL}InventoryWeb/PostPartCategory`,
  PostGlAccounts: `${API_BASE_URL}InventoryWeb/PostGlAccounts`,
  
  GetGlAccountGroup: `${API_BASE_URL}/InventoryWeb/GetGlAccountGroup`,
  PostGlAccountGroup: `${API_BASE_URL}InventoryWeb/PostGlAccountGroup`,
};
export const ItemMaster = {
  GetPartsList: `${API_BASE_URL}ItemMaster/GetPartsList`,
  GetGlAccounts: `${API_BASE_URL}ItemMaster/GetGlAccounts`,
  GetRelatedProductList: `${API_BASE_URL}Administration/GetRelatedProductList`,
  PostRelatedProduct: `${API_BASE_URL}Administration/PostRelatedProduct`,
  
  GetKitList: `${API_BASE_URL}ItemMaster/GetKitList`,
  GetKit: `${API_BASE_URL}ItemMaster/GetKit`,
  GetPartDetail: `${API_BASE_URL}ItemMaster/GetPartDetails`,
  PostPartDetails: `${API_BASE_URL}ItemMaster/PostPartDetails`,
  GetPartsUomSearch: `${API_BASE_URL}ItemMaster/GetPartsUom`,
  GetItemListing: `${API_BASE_URL}ItemMaster/GetItemListing`,
  GetPartsUom: `${API_BASE_URL}ItemMaster/GetPartsUom`,
  GetWarehouse: `${API_BASE_URL}InventoryWeb/GetWarehouse`,
  GetPartOnhandAvlQty: `${API_BASE_URL}InventoryWeb/GetPartOnhandAvlQty`,
  GetSupplierCode: `${API_BASE_URL}InventoryWeb/GetSupplierCode`,
  // PostAttachmentFile: `${API_BASE_URL}ITEMMASTER/PostAttachmentFile`,
  PostFileBase64: `${API_BASE_URL}ItemMaster/PostFileBase64`,
  GetPartAttachments: `${API_BASE_URL}ITEMMASTER/GetPartAttachments`,
  DeleteAttachment: `${API_BASE_URL}ITEMMASTER/DeleteAttachment`,
  PostTempFiles: `${API_BASE_URL}ITEMMASTER/PostTempFiles`,
  PostAttachmentFile: `${API_BASE_URL}ITEMMASTER/PostAttachmentFile`,
  PostLotDetail: `${API_BASE_URL}InventoryWeb/PostLotDetail`,
  PostLotReleaseFlag: `${API_BASE_URL}InventoryWeb/PostLotReleaseFlag`,
  GetCodeUniqueValidation: `${API_BASE_URL}InventoryWeb/GetCodeUniqueValidation`,
  PostKit: `${API_BASE_URL}ItemMaster/PostKit`,
  PostKitDetail: `${API_BASE_URL}ItemMaster/PostKitDetail`,
  GetBoltonPartsList: `${API_BASE_URL}ItemMaster/GetBoltonPartsList`,
  GetKitDetails: `${API_BASE_URL}ItemMaster/GetKitDetails`,
  ItemMasterPDFReport: `${API_BASE_URL}ItemMaster/ItemMasterPDFReport`,
  PickOrderListPDFReport: `${API_BASE_URL}InventoryWeb/PickOrderListPDFReport`,
  PostDuplicatePart: `${API_BASE_URL}Inventory/PostDuplicatePart`,
  PostDuplicatePartLot: `${API_BASE_URL}Inventory/PostDuplicatePartLot`,
};
export const Purchase = {
  GetAuditLog: `${API_BASE_URL}InventoryWeb/GetAuditLog`,
  GetPurchaseList: `${API_BASE_URL}InventoryWeb/GetPurchaseOrderList`,
  GetPurchaseOrderList: `${API_BASE_URL}InventoryWeb/GetPurchaseOrderList`,
  GetPurchaseLotList: `${API_BASE_URL}InventoryWeb/GetPurchaseLotList`,
  GetPOById: `${API_BASE_URL}InventoryWeb/GetPurchaseOrder`,
  PostPODetails: `${API_BASE_URL}InventoryWeb/PostPurchaseOrderDetails`,
  PostPurchaseOrder: `${API_BASE_URL}InventoryWeb/PostPurchaseOrder`,
  PostsplitPO: `${API_BASE_URL}InventoryWeb/PostSplitPurchaseOrder`,
  PostReversePO: `${API_BASE_URL}InventoryWeb/PostReversePO`,
  PostReversePickOrder: `${API_BASE_URL}InventoryWeb/PostReversePickOrder`,
};
export const Receiving = {
  PostRecievingDetail: `${API_BASE_URL}InventoryWeb/PostRecievingDetail`,
  PostRecieving: `${API_BASE_URL}InventoryWeb/PostRecieving`,
  PostFinalizedRecieving: `${API_BASE_URL}InventoryWeb/PostFinalizedRecieving`,
  GetRecieving: `${API_BASE_URL}InventoryWeb/GetRecieving`,
  GetRecievingList: `${API_BASE_URL}InventoryWeb/GetRecievingList`,
  GetAuditLog: `${API_BASE_URL}InventoryWeb/GetAuditLog`,
  PostRecievingByPO: `${API_BASE_URL}InventoryWeb/PostRecievingByPO`,
  PostRecievingFromPO: `${API_BASE_URL}InventoryWeb/PostRecievingFromPO`,
};
export const StockOrder = {
  PostStockOrder: `${API_BASE_URL}InventoryWeb/PostStockOrder`,
  StockOrderPDFReport: `${API_BASE_URL}InventoryWeb/StockOrderPDFReport`,
  PostStockOrderDetail: `${API_BASE_URL}InventoryWeb/PostStockOrderDetail`,
  PostAutoStockOrder: `${API_BASE_URL}InventoryWeb/PostAutoStockOrder`,
  PostReSyncSaleOrder: `${API_BASE_URL}InventoryWeb/PostReSyncSaleOrder`,
  GetStockOrder: `${API_BASE_URL}InventoryWeb/GetStockOrder`,
  GetStockOrderList: `${API_BASE_URL}InventoryWeb/GetStockOrderList`,
  GetStockLocationID: `${API_BASE_URL}InventoryWeb/GetStockLocationID`,
  PostFinalizedStockOrder: `${API_BASE_URL}InventoryWeb/PostFinalizedStockOrder`,
};
export const General = {
  GetCountryList: `${API_BASE_URL}InventoryWeb/GetCountryList`,
  GetProvinceState: `${API_BASE_URL}InventoryWeb/GetProvinceState`,
  GetCustomerGroups: `${API_BASE_URL}InventoryWeb/GetCustomerGroups`,
  GetChannels: `${API_BASE_URL}InventoryWeb/GetChannels`,
  GetCustomer: `${API_BASE_URL}InventoryWeb/GetCustomer`,
  PostCustomerGroup: `${API_BASE_URL}InventoryWeb/PostCustomerGroup`,
  PostUOW: `${API_BASE_URL}Administration/PostUOW`,
  // GetUowCode: `${API_BASE_URL}InventoryWeb/GetUowCode`,
  GetUowCode: `${API_BASE_URL}InventoryWeb/GetUowCode`,
  GetFrequentSaleItems: `${API_BASE_URL}InventoryWeb/GetFrequentSaleItems`,
  GetPartLocOnhand: `${API_BASE_URL}InventoryWeb/GetPartLocOnhand`,
  GetDuplicatePartLots: `${API_BASE_URL}Inventory/GetDuplicatePartLots`,
};
export const Sales = {
  PostSaleOrder: `${API_BASE_URL}InventoryWeb/PostSaleOrder`,
  PostSaleOrderDetail: `${API_BASE_URL}InventoryWeb/PostSaleOrderDetail`,
  GetSaleOrder: `${API_BASE_URL}InventoryWeb/GetSaleOrder`,
  GetSaleOrderDetail: `${API_BASE_URL}InventoryWeb/GetSaleOrderDetail`,
  GetCustomer: `${API_BASE_URL}InventoryWeb/GetCustomer`,
  GetSaleOrderList: `${API_BASE_URL}InventoryWeb/GetSaleOrderList`,
  GetSaleOrderReturnList: `${API_BASE_URL}InventoryWeb/GetSaleOrderReturnList`,
  GetChannels: `${API_BASE_URL}InventoryWeb/GetChannels`,
  PostSaleOrderTaxes: `${API_BASE_URL}InventoryWeb/PostSaleOrderTaxes`,
  GetSaleOrderDetailAutoList: `${API_BASE_URL}InventoryWeb/GetSaleOrderDetailAutoList`,
  GetSaleOrderDetailNPAutoList: `${API_BASE_URL}InventoryWeb/GetSaleOrderDetailNPAutoList`,
  PostFinalizedSaleOrder: `${API_BASE_URL}InventoryWeb/PostFinalizedSaleOrder`,
  PostAutoSaleOrder: `${API_BASE_URL}InventoryWeb/PostAutoSaleOrder`,
};
export const PickOrder = {
  GetPickOrderList: `${API_BASE_URL}InventoryWeb/GetPickOrderList`,
};
export const PhysicalCount = {
  GetPhysicalCount: `${API_BASE_URL}InventoryWeb/GetPhysicalCount`,
  GetPhysicalCountDetails: `${API_BASE_URL}InventoryWeb/GetPhysicalCountDetails`,
  GetPhysicalCountNumber: `${API_BASE_URL}InventoryWeb/GetPhysicalCountNumber`,
  GetPhysicalCountList: `${API_BASE_URL}InventoryWeb/GetPhysicalCountList`,
  GetPhysicalCountFilterSearch: `${API_BASE_URL}InventoryWeb/GetPhysicalCountFilterSearch`,
  PostPhysicalCount: `${API_BASE_URL}InventoryWeb/PostPhysicalCount`,
  PostPhysicalCountDetail: `${API_BASE_URL}InventoryWeb/PostPhysicalCountDetail`,
  PostFinalizePhysicalCount: `${API_BASE_URL}InventoryWeb/PostFinalizePhysicalCount`,
  // PostFinalizePhysicalCount: `${API_BASE_URL}InventoryWeb/PostFinalizePhysicalCount`,
  GetAutoPCDetailList: `${API_BASE_URL}InventoryWeb/GetAutoPCDetailList`,
  GetAutoCycleCountDetList: `${API_BASE_URL}InventoryWeb/GetAutoCycleCountDetList`,
  GetWarehouse: `${API_BASE_URL}InventoryWeb/GetWarehouse`,
  GetUserList: `${API_BASE_URL}Security/GetUserList`,
};
export const Transfer = {
  GetAutoTransferDetailsList: `${API_BASE_URL}InventoryWeb/GetAutoTransferDetailsList`,
  GetInvTransferListPDFReport: `${API_BASE_URL}InventoryWeb/GetInvTransferListPDFReport`,
  GetInvTransferList: `${API_BASE_URL}InventoryWeb/GetInvTransferList`,
  GetInvTransfer: `${API_BASE_URL}InventoryWeb/GetInvTransfer`,
  PostInventoryTransfer: `${API_BASE_URL}InventoryWeb/PostInventoryTransfer`,
  PostInventoryTransferDetails: `${API_BASE_URL}InventoryWeb/PostInventoryTransferDetails`,
  PostTransferFinalized: `${API_BASE_URL}InventoryWeb/PostTransferFinalized`,
  PostPartCategory: `${API_BASE_URL}InventoryWeb/PostPartCategory`,
  GetProvinceState: `${API_BASE_URL}InventoryWeb/GetProvinceState`,
};
export const Administration = {
  GetFiscalYearList:`${API_BASE_URL}Administration/GetFiscalYearList`,
  PostFiscalYear:`${API_BASE_URL}Administration/PostFiscalYear`,
  PostInvWarehousesPriority: `${API_BASE_URL}InventoryWeb/PostInvWarehousesPriority`,
  GetPartContents: `${API_BASE_URL}InventoryWeb/GetPartContents`,
  PostPartContents: `${API_BASE_URL}InventoryWeb/PostPartContents`,
  GetPartCategoryList: `${API_BASE_URL}InventoryWeb/GetPartCategoryList`,
  GetPartBrandList: `${API_BASE_URL}InventoryWeb/GetPartBrandList`,
  PostPartBrands: `${API_BASE_URL}InventoryWeb/PostPartBrands`,
  GetUoWList: `${API_BASE_URL}InventoryWeb/GetUowList`,
  PostInventoryWarehouse: `${API_BASE_URL}InventoryWeb/PostInventoryWarehouse`,
  GetInventoryWarehouses: `${API_BASE_URL}InventoryWeb/GetInventoryWarehouses`,
  // GetProvinceState: `${API_BASE_URL}InventoryWeb/GetProvinceState`,
  PostCustomerDropShipAddress: `${API_BASE_URL}Administration/PostCustomerDropShipAddress`,
  GetCustomerDropShipAddressList: `${API_BASE_URL}Administration/GetCustomerDropShipAddressList`,
  GetCustomerDropShipAddressDetails: `${API_BASE_URL}Administration/GetCustomerDropShipAddressDetails`,
  GetPartPriceList: `${API_BASE_URL}Administration/GetPartPriceList`,
  GetLocationDetails: `${API_BASE_URL}Administration/GetLocationDetails`,
  PostPaymentTerm: `${API_BASE_URL}Administration/PostPaymentTerm`,
  PostCustomerBranch: `${API_BASE_URL}Administration/PostCustomerBranch`,
  GetCustomerBranch: `${API_BASE_URL}Administration/GetCustomerBranch`,
  GetCustomerPromosList: `${API_BASE_URL}Administration/GetCustomerPromosList`,
  PostCustomerPromos: `${API_BASE_URL}Administration/PostCustomerPromos`,
  PostPromotions: `${API_BASE_URL}Administration/PostPromotions`,
  GetCustomerARTaxes: `${API_BASE_URL}Administration/GetCustomerARTaxes`,
  PostCustomerARTaxes: `${API_BASE_URL}Administration/PostCustomerARTaxes`,
  GetCustomerBranchList: `${API_BASE_URL}Administration/GetCustomerBranchList`,
  PostDiscountGroup: `${API_BASE_URL}Administration/PostDiscountGroup`,
  PostProductType: `${API_BASE_URL}Administration/PostProductType`,
  GetProductType: `${API_BASE_URL}Administration/GetProductTypeList`,
  PostCustomers: `${API_BASE_URL}Administration/PostCustomers`,
  GetPurchaseGroupList: `${API_BASE_URL}InventoryWeb/GetPurchaseGroupList`,
  PostPurchaseGroup: `${API_BASE_URL}InventoryWeb/PostPurchaseGroup`,
  GetCountryList: `${API_BASE_URL}InventoryWeb/GetCountryList`,
  GetEditScreenSessionsList: `${API_BASE_URL}Inventory/GetEditScreenSessionsList`,
  GetShippingBoxList: `${API_BASE_URL}Administration/GetShippingBoxList`,
  GetShipCarrierList: `${API_BASE_URL}Administration/GetShipCarrierList`,
  PostShipCarrier: `${API_BASE_URL}Administration/PostShipCarrier`,
  GetDiscountList: `${API_BASE_URL}Administration/GetDiscountGroupList`,
  GetCorporateList: `${API_BASE_URL}Administration/GetCorporateList`,
  GetWarehousesList: `${API_BASE_URL}Administration/GetWarehousesList`,
  GetBranchList: `${API_BASE_URL}Administration/GetBranchList`,
  GetPromotionList: `${API_BASE_URL}Administration/GetPromotionList`,
  GetVendors: `${API_BASE_URL}Administration/GetVendors`,
  GetPromotions: `${API_BASE_URL}Administration/GetPromotions`,
  GetCustomerDetails: `${API_BASE_URL}Administration/GetCustomerDetails`,
  GetCustomersList: `${API_BASE_URL}Administration/GetCustomersList`,
  GetPartLotALLList: `${API_BASE_URL}Administration/GetPartLotALLList`,
  GetPartLotList: `${API_BASE_URL}Administration/GetPartLotList`,
  // GetCustomerDropShipAddressList: `${API_BASE_URL}Administration/GetCustomerDropShipAddressList`,
  GetUoMList: `${API_BASE_URL}Administration/GetUomList`,
  GetPaymentTermList: `${API_BASE_URL}Administration/GetPaymentTermList`,
  GetTaxesList: `${API_BASE_URL}Administration/GetTaxesList`,
  PostTaxes: `${API_BASE_URL}Administration/PostTaxes`,
  GetSupplierList: `${API_BASE_URL}Administration/GetSupplierList`,
  GetStatesProvincesOfCountry: `${API_BASE_URL}Administration/GetStatesProvincesOfCountry`,
  GetAllCountries: `${API_BASE_URL}Administration/GetAllCountries`,
  GetPartNameOverrides: `${API_BASE_URL}Administration/GetPartNameOverrides`,
  PostPartNameOverrides: `${API_BASE_URL}Administration/PostPartNameOverrides`,
  PostPartPriceOverride: `${API_BASE_URL}Administration/PostPartPriceOverride`,
  GetPartPriceOverride: `${API_BASE_URL}Administration/GetPartPriceOverride`,
  PostPartPriceList: `${API_BASE_URL}Administration/PostPartPriceList`,
  GetWareHouseLocations: `${API_BASE_URL}Administration/GetWarehouseLocationList`,
  GetAdminAccess: `${API_BASE_URL}Administration/GetAdminAccess`,
  GetDistinctPartLotList: `${API_BASE_URL}Administration/GetDistinctPartLotList`,
  PostHarmonizedTarrifCode: `${API_BASE_URL}Administration/PostHarmonizedTarrifCode`,
  GetHarmonizedTarrifCodeList: `${API_BASE_URL}Administration/GetHarmonizedTarrifCodeList`,
  GetHarmonizedTarrifCode: `${API_BASE_URL}Administration/GetHarmonizedTarrifCode`,
  PostPartCost: `${API_BASE_URL}Administration/PostPartCost`,
  PostUOM: `${API_BASE_URL}Administration/PostUOM`,
  GetPartCost: `${API_BASE_URL}Administration/GetPartCost`,
  PostPartPrice: `${API_BASE_URL}Administration/PostPartPrice`,
  GetPartPrice: `${API_BASE_URL}Administration/GetPartPrice`,
  GetPartGroupList: `${API_BASE_URL}Administration/GetPartGroupList`,
  PostPartGroups: `${API_BASE_URL}Administration/PostPartGroups`,
  GetProductTypeList: `${API_BASE_URL}Administration/GetProductTypeList`,
  GetProductClassList: `${API_BASE_URL}Administration/GetProductClassList`,
  PostProductClass: `${API_BASE_URL}Administration/PostProductClass`,
  GetPartSubGroupList: `${API_BASE_URL}Administration/GetPartSubGroupList`,
  PostProductVariance: `${API_BASE_URL}Administration/PostProductVariance`,
  GetProductVarianceList: `${API_BASE_URL}Administration/GetProductVarianceList`,
  GetProductVariance: `${API_BASE_URL}Administration/GetProductVariance`,
  GetProductVarianceType: `${API_BASE_URL}Administration/GetProductVarianceType`,
  GetProductVarianceTypeList: `${API_BASE_URL}Administration/GetProductVarianceTypeList`,
  PostProductVarianceType: `${API_BASE_URL}Administration/PostProductVarianceType`,
  GetAdmProvinceStateTaxesList: `${API_BASE_URL}Administration/GetAdmProvinceStateTaxesList`,
  PostAdmProvinceStateTaxes: `${API_BASE_URL}Administration/PostAdmProvinceStateTaxes`,
  GetProvinceState: `${API_BASE_URL}Administration/GetProvinceState`,
  GetAdmShipCarrierDetailList: `${API_BASE_URL}Administration/GetAdmShipCarrierDetailList`,
  PostAdmShipCarrierDetail: `${API_BASE_URL}Administration/PostAdmShipCarrierDetail`,
   GetadmForexDetailsList: `${API_BASE_URL}AdministrationWeb/GetadmForexDetailsList`,
   PostAdmForexDetails: `${API_BASE_URL}AdministrationWeb/PostAdmForexDetails`,
   GetChannelList:`${API_BASE_URL}Administration/GetChannelList`,
   PostChannel:`${API_BASE_URL}Administration/PostChannel`,
};
export const SessionManagement = {
  PostEditScreenSessions: `${API_BASE_URL}Inventory/PostEditScreenSessions`,
  PostKillScreenSessions: `${API_BASE_URL}Inventory/PostKillScreenSessions`,
  GetEditScreenSessions: `${API_BASE_URL}Inventory/GetEditScreenSessions`,
};
export const DashboardApi = {
  GetDashboardPurgroTotal: `${API_BASE_URL}InventoryWeb/GetDashboardPurgroTotal`,
};