import { Figtree, Poppins } from "next/font/google";
import React from "react";
import "./globals.css";
import ReduxStoreProvider from "../redux/provider";
// import Sidebar from "../components/misc/Sidebar/Sidebar"
import Sidebar from "../components/misc/globalComponents/Sidebar/Sidebar";
import MobBotNav from "../components/misc/globalComponents/mobailBottomNav/MobaiBottomNav";
import Header from "../components/misc/globalComponents/header/Header";
// import figtree from '../utils/fonts'

const figtree_init = Figtree({ weight: "400", subsets: ["latin"] });
const poppins_init = Poppins({
  weight: ["500", "700"],
  subsets: ["latin"],
  variable: "--poppins-init",
});

export const metadata = {
  title: "EUT",
  description: "Generated by create next app",
};
// const token = localStorage.getItem("tokenSession");
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${figtree_init.className} ${poppins_init.variable}`}>
        <ReduxStoreProvider>
          {<Header />}
          <div className="flex ">
            {<Sidebar />}
            <div className=" h-[100vh] lg:pt-[7vh] md:pt-[7vh] sm:pt-[7vh]  w-full bg-[#E1EFF2] overflow-x-hidden pr-2 pb-2 ">
              <div className=" bg-white  w-full overflow-y-auto   max-h-full lg:rounded-tl-xl md:rounded-tl-xl sm:rounded-tl-xl rounded-tl-none h-[93vh]  flex flex-col">
                {children}
              </div>
            </div>
          </div>
          <MobBotNav />
        </ReduxStoreProvider>
      </body>
    </html>
  );
}
