export const payloadPartsList = {
  data: {
    SEARCH: "",
    ACTIVE_FLAG: "",
    OFFSET: "+4:00",
    ORDER: "PAR_ID DESC",
    RNUM_FROM: 1,
    RNUM_TO: 25,
  },
  action: "ItemMaster",
  method: "GetPartsList",
  username: "admin",
  type: "rpc",
  tid: "144",
};
export const payloadSpecial = {
  data: {
    SEARCH: "",
    ACTIVE_FLAG: "Y",
    BOLTON_FLAG: "N",
    NON_STOCK_FLAG: "N",
    OFFSET: "+4:00",
    ORDER: "PAR_ID DESC",
    RNUM_FROM: 1,
    RNUM_TO: 25,
    SPECIAL_FLAG: "Y",
  },
  action: "ItemMaster",
  method: "GetPartsList",
  username: "admin",
  type: "rpc",
  tid: "144",
};
export const payloadBolton = {
  data: {
    SEARCH: "",
    ACTIVE_FLAG: "Y",
    BOLTON_FLAG: "Y",
    NON_STOCK_FLAG: "N",
    OFFSET: "+4:00",
    ORDER: "PAR_ID DESC",
    RNUM_FROM: 1,
    RNUM_TO: 25,
    SPECIAL_FLAG: "N",
  },
  action: "ItemMaster",
  method: "GetPartsList",
  username: "admin",
  type: "rpc",
  tid: "144",
};
export const payloadNonStock = {
  data: {
    SEARCH: "",
    ACTIVE_FLAG: "Y",
    BOLTON_FLAG: "N",
    NON_STOCK_FLAG: "Y",
    OFFSET: "+4:00",
    ORDER: "PAR_ID DESC",
    RNUM_FROM: 1,
    RNUM_TO: 25,
    SPECIAL_FLAG: "N",
  },
  action: "ItemMaster",
  method: "GetPartsList",
  username: "admin",
  type: "rpc",
  tid: "144",
};
export const payloadInactive = {
  data: {
    SEARCH: "",
    ACTIVE_FLAG: "N",
    BOLTON_FLAG: "N",
    NON_STOCK_FLAG: "N",
    OFFSET: "+4:00",
    ORDER: "PAR_ID DESC",
    RNUM_FROM: 1,
    RNUM_TO: 25,
    SPECIAL_FLAG: "N",
  },
  action: "ItemMaster",
  method: "GetPartsList",
  username: "admin",
  type: "rpc",
  tid: "144",
};
export const PayloadKitList = {
  data: {
    ACTIVE_FLAG: "",
    OFFSET: "+4:00",
    ORDER: "KIT_ID DESC",
    RNUM_FROM: 1,
    RNUM_TO: 25,
  },
  method: "GetKitList",
  tid: "144",
  type: "rpc",
  username: "admin",
};
// export const payloadSubGrid = {
//   data: {
//     ACTIVE_FLAG: "Y",
//     EXPIRY_FLAG: "N",
//     ORDER: "",
//     PAR_ID: "",
//     RNUM_FROM: 1,
//     RNUM_TO: 25,
//     SEARCH: "",
//     WAR_ID: "",
//   },
//   method: "GetPartLotList",
//   tid: "144",
//   type: "rpc",
//   username: "admin",
// };
